POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxlZXZpbyIsImlkIjoiNjA3NmJhODQ3OTYwZWEzNDE5NGY5MzA2IiwiaWF0IjoxNjE4Mzk2MzQyfQ.vu105NURYTKPP9KG7VLPGh-NVpmfQMSmqjJX2vXTFXs

{
    "title": "Test with token",
    "author": "test author",
    "url": "test url",
    "likes": 18
}